### ISSUE TITLE
Meaning of _o and _l in residual_encoder

### ISSUE THREAD

**Issue by tshmak** [deterministic-algorithms-lab/Cross-Lingual-Voice-Cloning#5]
Hi @Jeevesh8 thanks a lot for your code! 

I am trying to understand the paper more. Can you please clarify the meaning of the subscripts `_o` and `_l` in [residual_encoder.py](https://github.com/deterministic-algorithms-lab/Cross-Lingual-Voice-Cloning/blob/master/residual_encoder.py)? I see that you are using two residual encoders and concatenating them, and they serve different purposes. 

Thanks a lot! 

Tim

**Comment by Jeevesh8** [comment]
They mean observed and latent respectively @tshmak . You can read this [paper](https://arxiv.org/abs/1810.07217) .
